In [1]:
from cson_forge import catalog

In [2]:
# instantiate catalog
# you could pass a different blueprint_dir to read a different catalog
# I am defaulting everything to "build" stage since that is the C-Star hand-off point
bp_catalog = catalog.BlueprintCatalog()

In [3]:
# show everything
bp_catalog.df

,model_name,grid_name,blueprint_name,description,start_time,end_time,blueprint_path,grid_yaml_path,stage
0,cson_roms-marbl_v0.1_GoA-10th_deg,128procs,cson_roms-marbl_v0.1_GoA-10th_deg_128procs,Gulf of Alaska 1/10 deg (nested),2012-01-01T00:00:00,2012-01-02T00:00:00,/Users/eilerman/git/cson-forge/cson_forge/blue...,/Users/eilerman/git/cson-forge/cson_forge/blue...,build
1,cson_roms-marbl_v0.1_NEP-4th_deg,128procs,cson_roms-marbl_v0.1_NEP-4th_deg_128procs,Northeast Pacific 1/4 deg (nested),2012-01-01T00:00:00,2012-01-02T00:00:00,/Users/eilerman/git/cson-forge/cson_forge/blue...,/Users/eilerman/git/cson-forge/cson_forge/blue...,build
2,cson_roms-marbl_v0.1_PAC_2fth_deg,128procs,cson_roms-marbl_v0.1_PAC_2fth_deg_128procs,Pacific 2/15 deg (nested),2012-01-01T00:00:00,2012-01-02T00:00:00,/Users/eilerman/git/cson-forge/cson_forge/blue...,/Users/eilerman/git/cson-forge/cson_forge/blue...,build
3,cson_roms-marbl_v0.1_ccs-12km,320procs,cson_roms-marbl_v0.1_ccs-12km_320procs,California Current System,2024-01-01T00:00:00,2024-01-02T00:00:00,/Users/eilerman/git/cson-forge/cson_forge/blue...,/Users/eilerman/git/cson-forge/cson_forge/blue...,build
4,cson_roms-marbl_v0.1_gulf-guinea-toy,10procs,cson_roms-marbl_v0.1_gulf-guinea-toy_10procs,Gulf of Guinea (toy),2012-01-01T00:00:00,2012-01-02T00:00:00,/Users/eilerman/git/cson-forge/cson_forge/blue...,/Users/eilerman/git/cson-forge/cson_forge/blue...,build
...,...,...,...,...,...,...,...,...,...
65,cson_roms-no-bgc_v0.1_ccs-12km_352procs,040,cson_roms-no-bgc_v0.1_ccs-12km_352procs_040,California Current System,2024-01-01T00:00:00,2024-01-10T00:00:00,/Users/eilerman/git/cson-forge/cson_forge/blue...,/Users/eilerman/git/cson-forge/cson_forge/blue...,build
66,cson_roms-no-bgc_v0.1_ccs-12km_70procs,010,cson_roms-no-bgc_v0.1_ccs-12km_70procs_010,California Current System,2024-01-01T00:00:00,2024-01-10T00:00:00,/Users/eilerman/git/cson-forge/cson_forge/blue...,/Users/eilerman/git/cson-forge/cson_forge/blue...,build
67,cson_roms-no-bgc_v0.1_ccs-12km_70procs,020,cson_roms-no-bgc_v0.1_ccs-12km_70procs_020,California Current System,2024-01-01T00:00:00,2024-01-10T00:00:00,/Users/eilerman/git/cson-forge/cson_forge/blue...,/Users/eilerman/git/cson-forge/cson_forge/blue...,build
68,cson_roms-no-bgc_v0.1_ccs-12km_70procs,030,cson_roms-no-bgc_v0.1_ccs-12km_70procs_030,California Current System,2024-01-01T00:00:00,2024-01-10T00:00:00,/Users/eilerman/git/cson-forge/cson_forge/blue...,/Users/eilerman/git/cson-forge/cson_forge/blue...,build
69,cson_roms-no-bgc_v0.1_ccs-12km_70procs,040,cson_roms-no-bgc_v0.1_ccs-12km_70procs_040,California Current System,2024-01-01T00:00:00,2024-01-10T00:00:00,/Users/eilerman/git/cson-forge/cson_forge/blue...,/Users/eilerman/git/cson-forge/cson_forge/blue...,build

In [4]:
# something like a domain list
bp_catalog.df["description"].unique()

<ArrowStringArray>
[  'Gulf of Alaska 1/10 deg (nested)', 'Northeast Pacific 1/4 deg (nested)',
          'Pacific 2/15 deg (nested)',          'California Current System',
               'Gulf of Guinea (toy)',               'Hvalfjörður, Iceland',
                'Generated blueprint',                          'Test tiny',
         'Western Indian Ocean (toy)',           'Pacific 1/2 deg (nested)']
Length: 10, dtype: str

In [5]:
# added functionality to search for keywords
bp_catalog.search("tiny")

,model_name,grid_name,blueprint_name,description,start_time,end_time,blueprint_path,grid_yaml_path,stage
8,cson_roms-marbl_v0.1_test-tiny,1procs,cson_roms-marbl_v0.1_test-tiny_1procs,Test tiny,2012-01-01T00:00:00,2012-01-02T00:00:00,/Users/eilerman/git/cson-forge/cson_forge/blue...,/Users/eilerman/git/cson-forge/cson_forge/blue...,build
10,cson_roms-no-bgc_v0.1_test-tiny,1procs,cson_roms-no-bgc_v0.1_test-tiny_1procs,Test tiny,2012-01-01T00:00:00,2012-01-02T00:00:00,/Users/eilerman/git/cson-forge/cson_forge/blue...,/Users/eilerman/git/cson-forge/cson_forge/blue...,build
49,cson_roms-marbl_v0.1,test-tiny,cson_roms-marbl_v0.1_test-tiny,Test tiny,2012-01-01T00:00:00,2012-01-02T00:00:00,/Users/eilerman/git/cson-forge/cson_forge/blue...,/Users/eilerman/git/cson-forge/cson_forge/blue...,build

In [6]:
# you can pass any kwargs, e.g. blueprint name, and it will run if there's only one result, or error if its ambiguous
# index is an easy one if you already identified your BP above
# this runs via cstar cli in the background
bp_catalog.run(index=8)

Running cstar blueprint run /Users/eilerman/git/cson-forge/cson_forge/blueprints/MacOS/cson_roms-marbl_v0.1_test-tiny_1procs/B_cson_roms-marbl_v0.1_test-tiny_1procs_build.yml
2026-05-15 15:37:30,217 [INFO] - simulation.py:1288 - 🛠️ Configuring ROMSSimulation
2026-05-15 15:37:30,218 [INFO] - simulation.py:1291 - 🔧 Setting up ROMSExternalCodeBase...
2026-05-15 15:37:39,210 [INFO] - simulation.py:1291 - 🔧 Setting up MARBLExternalCodeBase...
2026-05-15 15:37:53,004 [INFO] - simulation.py:1305 - 📦 Fetching compile-time code...
2026-05-15 15:37:53,010 [INFO] - simulation.py:1310 - 📦 Fetching runtime code...
2026-05-15 15:37:53,011 [INFO] - simulation.py:1315 - 📦 Fetching input datasets...
2026-05-15 15:37:53,015 [INFO] - input_dataset.py:97 - 🔗 Created symlink: /Users/eilerman/cson-forge-data/cson-forge-run/cson_roms-marbl_v0.1_test-tiny_1procs_20120101-20120102/work/cdr.nc → /Users/eilerman/cson-forge-data/cson-forge-run/cson_roms-marbl_v0.1_test-tiny_1procs_20120101-20120102/input/input_datasets/cson_roms-marbl_v0_1_test-tiny_1procs_cdr.nc
2026-05-15 15:38:03,446 [INFO] - input_dataset.py:279 - Partitioning /Users/eilerman/cson-forge-data/cson-forge-run/cson_roms-marbl_v0.1_test-tiny_1procs_20120101-20120102/input/input_datasets/cson_roms-marbl_v0_1_test-tiny_1procs_grid.nc into (1,1)
2026-05-15 15:38:08,630 [INFO] - input_dataset.py:279 - Partitioning /Users/eilerman/cson-forge-data/cson-forge-run/cson_roms-marbl_v0.1_test-tiny_1procs_20120101-20120102/input/input_datasets/cson_roms-marbl_v0_1_test-tiny_1procs_initial_conditions.nc into (1,1)
2026-05-15 15:38:08,657 [INFO] - input_dataset.py:279 - Partitioning /Users/eilerman/cson-forge-data/cson-forge-run/cson_roms-marbl_v0.1_test-tiny_1procs_20120101-20120102/input/input_datasets/cson_roms-marbl_v0_1_test-tiny_1procs_tidal.nc into (1,1)
2026-05-15 15:38:08,663 [INFO] - input_dataset.py:279 - Partitioning /Users/eilerman/cson-forge-data/cson-forge-run/cson_roms-marbl_v0.1_test-tiny_1procs_20120101-20120102/input/input_datasets/cson_roms-marbl_v0_1_test-tiny_1procs_river.nc into (1,1)
2026-05-15 15:38:08,672 [INFO] - input_dataset.py:279 - Partitioning /Users/eilerman/cson-forge-data/cson-forge-run/cson_roms-marbl_v0.1_test-tiny_1procs_20120101-20120102/input/input_datasets/cson_roms-marbl_v0_1_test-tiny_1procs_boundary-physics_201112.nc into (1,1)
2026-05-15 15:38:08,684 [INFO] - input_dataset.py:279 - Partitioning /Users/eilerman/cson-forge-data/cson-forge-run/cson_roms-marbl_v0.1_test-tiny_1procs_20120101-20120102/input/input_datasets/cson_roms-marbl_v0_1_test-tiny_1procs_boundary-physics_201201.nc into (1,1)
2026-05-15 15:38:08,694 [INFO] - input_dataset.py:279 - Partitioning /Users/eilerman/cson-forge-data/cson-forge-run/cson_roms-marbl_v0.1_test-tiny_1procs_20120101-20120102/input/input_datasets/cson_roms-marbl_v0_1_test-tiny_1procs_boundary-bgc_clim.nc into (1,1)
2026-05-15 15:38:08,731 [INFO] - input_dataset.py:279 - Partitioning /Users/eilerman/cson-forge-data/cson-forge-run/cson_roms-marbl_v0.1_test-tiny_1procs_20120101-20120102/input/input_datasets/cson_roms-marbl_v0_1_test-tiny_1procs_surface-physics_201112.nc into (1,1)
2026-05-15 15:38:08,739 [INFO] - input_dataset.py:279 - Partitioning /Users/eilerman/cson-forge-data/cson-forge-run/cson_roms-marbl_v0.1_test-tiny_1procs_20120101-20120102/input/input_datasets/cson_roms-marbl_v0_1_test-tiny_1procs_surface-physics_201201.nc into (1,1)
2026-05-15 15:38:08,746 [INFO] - input_dataset.py:279 - Partitioning /Users/eilerman/cson-forge-data/cson-forge-run/cson_roms-marbl_v0.1_test-tiny_1procs_20120101-20120102/input/input_datasets/cson_roms-marbl_v0_1_test-tiny_1procs_surface-bgc_clim.nc into (1,1)
2026-05-15 15:38:08,756 [INFO] - simulation.py:1671 - Running mpirun -n 1 ./roms cstar_generated_roms.in
2026-05-15 15:38:09,074 [INFO] - handler.py:195 -
2026-05-15 15:38:09,074 [INFO] - handler.py:195 -  Activated CPP configuration switches:
2026-05-15 15:38:09,074 [INFO] - handler.py:195 -  <cppdefs.opt>
2026-05-15 15:38:09,074 [INFO] - handler.py:195 -        CWORTHY                 EXACT_RESTARTS          NONLIN_EOS
2026-05-15 15:38:09,074 [INFO] - handler.py:195 -        SALINITY                SOLVE3D                 SPLIT_EOS
2026-05-15 15:38:09,074 [INFO] - handler.py:195 -        TIDES                   UV_ADV                  UV_COR
2026-05-15 15:38:09,074 [INFO] - handler.py:195 -        CDR_FORCING             CURVGRID                MASKING
2026-05-15 15:38:09,074 [INFO] - handler.py:195 -        SPHERICAL               SPONGE                  BULK_FRC
2026-05-15 15:38:09,074 [INFO] - handler.py:195 -        M2_FRC_BRY              M3_FRC_BRY              OBC_EAST
2026-05-15 15:38:09,074 [INFO] - handler.py:195 -        OBC_M2FLATHER           OBC_M3ORLANSKI          OBC_NORTH
2026-05-15 15:38:09,074 [INFO] - handler.py:195 -        OBC_TORLANSKI           T_FRC_BRY               Z_FRC_BRY
2026-05-15 15:38:09,074 [INFO] - handler.py:195 -        LMD_BKPP                LMD_KPP                 LMD_MIXING
2026-05-15 15:38:09,074 [INFO] - handler.py:195 -        LMD_NONLOCAL            LMD_RIMIX               TS_DIF2
2026-05-15 15:38:09,074 [INFO] - handler.py:195 -        UV_VIS2                 MARBL                   MARBL_DIAGS
2026-05-15 15:38:09,074 [INFO] - handler.py:195 -        NHY_FORCING             NOX_FORCING             PCO2AIR_FORCING
2026-05-15 15:38:09,074 [INFO] - handler.py:195 -  <pre_step3d4S.F>
2026-05-15 15:38:09,074 [INFO] - handler.py:195 -        SPLINE_UV               SPLINE_TS
2026-05-15 15:38:09,074 [INFO] - handler.py:195 -  <step3d_uv1.F>
2026-05-15 15:38:09,074 [INFO] - handler.py:195 -        UPSTREAM_UV             SPLINE_UV
2026-05-15 15:38:09,074 [INFO] - handler.py:195 -  <step3d_uv2.F>
2026-05-15 15:38:09,074 [INFO] - handler.py:195 -        DELTA=0.2800000000000000EPSIL=0.35999999999999999
2026-05-15 15:38:09,074 [INFO] - handler.py:195 -  <step3d_t_ISO.F>
2026-05-15 15:38:09,074 [INFO] - handler.py:195 -        UPSTREAM_TS             SPLINE_TS
2026-05-15 15:38:09,074 [INFO] - handler.py:195 -  <set_depth.F>
2026-05-15 15:38:09,074 [INFO] - handler.py:195 -        NOW=3.63                MID=4.47                BAK=2.05
2026-05-15 15:38:09,074 [INFO] - handler.py:195 -        (N-M+B-1)/B=0.102439024
2026-05-15 15:38:09,074 [INFO] - handler.py:195 -  <lmd_kpp.F>
2026-05-15 15:38:09,074 [INFO] - handler.py:195 -        INT_AT_RHO_POINTS       SMOOTH_HBL
2026-05-15 15:38:09,074 [INFO] - handler.py:195 -  <set_global_definitions.h>
2026-05-15 15:38:09,074 [INFO] - handler.py:195 -        CORR_COUPLED_MODE       EXTRAP_BAR_FLUXES       IMPLCT_NO_SLIP_BTTM_BC
2026-05-15 15:38:09,074 [INFO] - handler.py:195 -
2026-05-15 15:38:09,074 [INFO] - handler.py:195 -  Git hash: xxx
2026-05-15 15:38:09,074 [INFO] - handler.py:195 - No SLURM or PBS job ID found.
2026-05-15 15:38:09,074 [INFO] - handler.py:195 -
2026-05-15 15:38:09,074 [INFO] - handler.py:195 -      cson_roms-marbl_v0.1_test-tiny_1procs_20120101-20120102
2026-05-15 15:38:09,074 [INFO] - handler.py:195 -      ntimes =        12   total number of 3D timesteps
2026-05-15 15:38:09,074 [INFO] - handler.py:195 -          dt =  7200.0000  time step [sec] for 3D equations
2026-05-15 15:38:09,074 [INFO] - handler.py:195 -     ndtfast =        60   mode-splitting ratio
2026-05-15 15:38:09,074 [INFO] - handler.py:195 -       ninfo =         1   number of steps between runtime diagnostics
2026-05-15 15:38:09,074 [INFO] - handler.py:195 -        rdrg = 0.000E+00  linear bottom drag coefficient [m/s]
2026-05-15 15:38:09,074 [INFO] - handler.py:195 -       rdrg2 = 1.000E-03  quadratic bottom drag coefficient, nondim
2026-05-15 15:38:09,074 [INFO] - handler.py:195 -         Zob = 1.000E-02  bottom roughness height [m]
2026-05-15 15:38:09,074 [INFO] - handler.py:195 -  initial condition :: rec =  1  file = '/Users/eilerman/cson-forge-data/cson-forge-run/cson_roms-marbl_v0.1_test-tiny_1procs_20120101-20120102/input/input_datasets/cson_roms-marbl_v0_1_test-tiny_1procs_initial_conditions.0.nc'
2026-05-15 15:38:09,074 [INFO] - handler.py:195 -  forcing data file(s): /Users/eilerman/cson-forge-data/cson-forge-run/cson_roms-marbl_v0.1_test-tiny_1procs_20120101-20120102/input/input_datasets/cson_roms-marbl_v0_1_test-tiny_1procs_tidal.0.nc
2026-05-15 15:38:09,075 [INFO] - handler.py:195 -                        /Users/eilerman/cson-forge-data/cson-forge-run/cson_roms-marbl_v0.1_test-tiny_1procs_20120101-20120102/input/input_datasets/cson_roms-marbl_v0_1_test-tiny_1procs_river.0.nc
2026-05-15 15:38:09,075 [INFO] - handler.py:195 -                        /Users/eilerman/cson-forge-data/cson-forge-run/cson_roms-marbl_v0.1_test-tiny_1procs_20120101-20120102/input/input_datasets/cson_roms-marbl_v0_1_test-tiny_1procs_surface-physics_201112.0.nc
2026-05-15 15:38:09,075 [INFO] - handler.py:195 -                        /Users/eilerman/cson-forge-data/cson-forge-run/cson_roms-marbl_v0.1_test-tiny_1procs_20120101-20120102/input/input_datasets/cson_roms-marbl_v0_1_test-tiny_1procs_surface-physics_201201.0.nc
2026-05-15 15:38:09,075 [INFO] - handler.py:195 -                        /Users/eilerman/cson-forge-data/cson-forge-run/cson_roms-marbl_v0.1_test-tiny_1procs_20120101-20120102/input/input_datasets/cson_roms-marbl_v0_1_test-tiny_1procs_surface-bgc_clim.0.nc
2026-05-15 15:38:09,075 [INFO] - handler.py:195 -                        /Users/eilerman/cson-forge-data/cson-forge-run/cson_roms-marbl_v0.1_test-tiny_1procs_20120101-20120102/input/input_datasets/cson_roms-marbl_v0_1_test-tiny_1procs_boundary-physics_201112.0.nc
2026-05-15 15:38:09,075 [INFO] - handler.py:195 -                        /Users/eilerman/cson-forge-data/cson-forge-run/cson_roms-marbl_v0.1_test-tiny_1procs_20120101-20120102/input/input_datasets/cson_roms-marbl_v0_1_test-tiny_1procs_boundary-physics_201201.0.nc
2026-05-15 15:38:09,075 [INFO] - handler.py:195 -                        /Users/eilerman/cson-forge-data/cson-forge-run/cson_roms-marbl_v0.1_test-tiny_1procs_20120101-20120102/input/input_datasets/cson_roms-marbl_v0_1_test-tiny_1procs_boundary-bgc_clim.0.nc
2026-05-15 15:38:09,075 [INFO] - handler.py:195 -
2026-05-15 15:38:09,075 [INFO] - handler.py:195 -     theta_s = 5.0000000  vertical S-coordinate surface
2026-05-15 15:38:09,075 [INFO] - handler.py:195 -     theta_b = 2.0000000  and bottom stretching parameters
2026-05-15 15:38:09,075 [INFO] - handler.py:195 -          hc = 250.00000  critical depth [m]
2026-05-15 15:38:09,075 [INFO] - handler.py:195 -  grid file: /Users/eilerman/cson-forge-data/cson-forge-run/cson_roms-marbl_v0.1_test-tiny_1procs_20120101-20120102/input/input_datasets/cson_roms-marbl_v0_1_test-tiny_1procs_grid.0.nc
2026-05-15 15:38:09,075 [INFO] - handler.py:195 -  MARBL namelist file               /Users/eilerman/cson-forge-data/cson-forge-run/cson_roms-marbl_v0.1_test-tiny_1procs_20120101-20120102/input/runtime_code/marbl_in
2026-05-15 15:38:09,075 [INFO] - handler.py:195 -  MARBL tracer output list                                                   file     /Users/eilerman/cson-forge-data/cson-forge-run/cson_roms-marbl_v0.1_test-tiny_1procs_20120101-20120102/input/runtime_code/marbl_tracer_output_list
2026-05-15 15:38:09,075 [INFO] - handler.py:195 -  MARBL diagnostic output list                                                file /Users/eilerman/cson-forge-data/cson-forge-run/cson_roms-marbl_v0.1_test-tiny_1procs_20120101-20120102/input/runtime_code/marbl_diagnostic_output_list
2026-05-15 15:38:09,075 [INFO] - handler.py:195 -       visc2 = 0.000E+00  horizontal Laplacian kinematic viscosity [m^2/s]
2026-05-15 15:38:09,075 [INFO] - handler.py:195 -        rho0 = 1000.0000  Boussinesq reference density [kg/m^3].
2026-05-15 15:38:09,075 [INFO] - handler.py:195 -      gamma2 = 1.000E+00  slipperiness parameter: free-slip = +1, or no-slip = -1.
2026-05-15 15:38:09,075 [INFO] - handler.py:195 -    tnu2( 1) = 0.000E+00  horizontal Laplacian kinematic heat conductivity [m^2/s]
2026-05-15 15:38:09,075 [INFO] - handler.py:195 -    tnu2( 2) = 0.000E+00  horizontal Laplacian diffusion for tracer  2, [m^2/s]
2026-05-15 15:38:09,075 [INFO] - handler.py:195 -    tnu2( 3) = 0.000E+00  horizontal Laplacian diffusion for tracer  3, [m^2/s]
2026-05-15 15:38:09,075 [INFO] - handler.py:195 -    tnu2( 4) = 0.000E+00  horizontal Laplacian diffusion for tracer  4, [m^2/s]
2026-05-15 15:38:09,075 [INFO] - handler.py:195 -    tnu2( 5) = 0.000E+00  horizontal Laplacian diffusion for tracer  5, [m^2/s]
2026-05-15 15:38:09,075 [INFO] - handler.py:195 -    tnu2( 6) = 0.000E+00  horizontal Laplacian diffusion for tracer  6, [m^2/s]
2026-05-15 15:38:09,075 [INFO] - handler.py:195 -    tnu2( 7) = 0.000E+00  horizontal Laplacian diffusion for tracer  7, [m^2/s]
2026-05-15 15:38:09,075 [INFO] - handler.py:195 -    tnu2( 8) = 0.000E+00  horizontal Laplacian diffusion for tracer  8, [m^2/s]
2026-05-15 15:38:09,075 [INFO] - handler.py:195 -    tnu2( 9) = 0.000E+00  horizontal Laplacian diffusion for tracer  9, [m^2/s]
2026-05-15 15:38:09,075 [INFO] - handler.py:195 -    tnu2(10) = 0.000E+00  horizontal Laplacian diffusion for tracer 10, [m^2/s]
2026-05-15 15:38:09,075 [INFO] - handler.py:195 -    tnu2(11) = 0.000E+00  horizontal Laplacian diffusion for tracer 11, [m^2/s]
2026-05-15 15:38:09,075 [INFO] - handler.py:195 -    tnu2(12) = 0.000E+00  horizontal Laplacian diffusion for tracer 12, [m^2/s]
2026-05-15 15:38:09,075 [INFO] - handler.py:195 -    tnu2(13) = 0.000E+00  horizontal Laplacian diffusion for tracer 13, [m^2/s]
2026-05-15 15:38:09,075 [INFO] - handler.py:195 -    tnu2(14) = 0.000E+00  horizontal Laplacian diffusion for tracer 14, [m^2/s]
2026-05-15 15:38:09,075 [INFO] - handler.py:195 -    tnu2(15) = 0.000E+00  horizontal Laplacian diffusion for tracer 15, [m^2/s]
2026-05-15 15:38:09,075 [INFO] - handler.py:195 -    tnu2(16) = 0.000E+00  horizontal Laplacian diffusion for tracer 16, [m^2/s]
2026-05-15 15:38:09,075 [INFO] - handler.py:195 -    tnu2(17) = 0.000E+00  horizontal Laplacian diffusion for tracer 17, [m^2/s]
2026-05-15 15:38:09,075 [INFO] - handler.py:195 -    tnu2(18) = 0.000E+00  horizontal Laplacian diffusion for tracer 18, [m^2/s]
2026-05-15 15:38:09,075 [INFO] - handler.py:195 -    tnu2(19) = 0.000E+00  horizontal Laplacian diffusion for tracer 19, [m^2/s]
2026-05-15 15:38:09,075 [INFO] - handler.py:195 -    tnu2(20) = 0.000E+00  horizontal Laplacian diffusion for tracer 20, [m^2/s]
2026-05-15 15:38:09,075 [INFO] - handler.py:195 -    tnu2(21) = 0.000E+00  horizontal Laplacian diffusion for tracer 21, [m^2/s]
2026-05-15 15:38:09,075 [INFO] - handler.py:195 -    tnu2(22) = 0.000E+00  horizontal Laplacian diffusion for tracer 22, [m^2/s]
2026-05-15 15:38:09,075 [INFO] - handler.py:195 -    tnu2(23) = 0.000E+00  horizontal Laplacian diffusion for tracer 23, [m^2/s]
2026-05-15 15:38:09,075 [INFO] - handler.py:195 -    tnu2(24) = 0.000E+00  horizontal Laplacian diffusion for tracer 24, [m^2/s]
2026-05-15 15:38:09,075 [INFO] - handler.py:195 -    tnu2(25) = 0.000E+00  horizontal Laplacian diffusion for tracer 25, [m^2/s]
2026-05-15 15:38:09,075 [INFO] - handler.py:195 -    tnu2(26) = 0.000E+00  horizontal Laplacian diffusion for tracer 26, [m^2/s]
2026-05-15 15:38:09,075 [INFO] - handler.py:195 -    tnu2(27) = 0.000E+00  horizontal Laplacian diffusion for tracer 27, [m^2/s]
2026-05-15 15:38:09,075 [INFO] - handler.py:195 -    tnu2(28) = 0.000E+00  horizontal Laplacian diffusion for tracer 28, [m^2/s]
2026-05-15 15:38:09,075 [INFO] - handler.py:195 -    tnu2(29) = 0.000E+00  horizontal Laplacian diffusion for tracer 29, [m^2/s]
2026-05-15 15:38:09,075 [INFO] - handler.py:195 -    tnu2(30) = 0.000E+00  horizontal Laplacian diffusion for tracer 30, [m^2/s]
2026-05-15 15:38:09,075 [INFO] - handler.py:195 -    tnu2(31) = 0.000E+00  horizontal Laplacian diffusion for tracer 31, [m^2/s]
2026-05-15 15:38:09,075 [INFO] - handler.py:195 -    tnu2(32) = 0.000E+00  horizontal Laplacian diffusion for tracer 32, [m^2/s]
2026-05-15 15:38:09,075 [INFO] - handler.py:195 -    tnu2(33) = 0.000E+00  horizontal Laplacian diffusion for tracer 33, [m^2/s]
2026-05-15 15:38:09,075 [INFO] - handler.py:195 -    tnu2(34) = 0.000E+00  horizontal Laplacian diffusion for tracer 34, [m^2/s]
2026-05-15 15:38:09,075 [INFO] - handler.py:195 -     Akv_bak = 0.000E+00  additional vertical viscosity [m^2/s]
2026-05-15 15:38:09,075 [INFO] - handler.py:195 -  Akt_bak(1) = 0.000E+00  additional vertical mixing [m^2/s] for tracer #1
2026-05-15 15:38:09,075 [INFO] - handler.py:195 -  Akt_bak(2) = 0.000E+00  additional vertical mixing [m^2/s] for tracer #2
2026-05-15 15:38:09,075 [INFO] - handler.py:195 -  Akt_bak(3) = 0.000E+00  additional vertical mixing [m^2/s] for tracer #3
2026-05-15 15:38:09,075 [INFO] - handler.py:195 -  Akt_bak(4) = 0.000E+00  additional vertical mixing [m^2/s] for tracer #4
2026-05-15 15:38:09,075 [INFO] - handler.py:195 -  Akt_bak(5) = 0.000E+00  additional vertical mixing [m^2/s] for tracer #5
2026-05-15 15:38:09,075 [INFO] - handler.py:195 -  Akt_bak(6) = 0.000E+00  additional vertical mixing [m^2/s] for tracer #6
2026-05-15 15:38:09,075 [INFO] - handler.py:195 -  Akt_bak(7) = 0.000E+00  additional vertical mixing [m^2/s] for tracer #7
2026-05-15 15:38:09,075 [INFO] - handler.py:195 -  Akt_bak(8) = 0.000E+00  additional vertical mixing [m^2/s] for tracer #8
2026-05-15 15:38:09,075 [INFO] - handler.py:195 -  Akt_bak(9) = 0.000E+00  additional vertical mixing [m^2/s] for tracer #9
2026-05-15 15:38:09,075 [INFO] - handler.py:195 -  Akt_bak(*) = 0.000E+00  additional vertical mixing [m^2/s] for tracer #10
2026-05-15 15:38:09,075 [INFO] - handler.py:195 -  Akt_bak(*) = 0.000E+00  additional vertical mixing [m^2/s] for tracer #11
2026-05-15 15:38:09,075 [INFO] - handler.py:195 -  Akt_bak(*) = 0.000E+00  additional vertical mixing [m^2/s] for tracer #12
2026-05-15 15:38:09,075 [INFO] - handler.py:195 -  Akt_bak(*) = 0.000E+00  additional vertical mixing [m^2/s] for tracer #13
2026-05-15 15:38:09,075 [INFO] - handler.py:195 -  Akt_bak(*) = 0.000E+00  additional vertical mixing [m^2/s] for tracer #14
2026-05-15 15:38:09,075 [INFO] - handler.py:195 -  Akt_bak(*) = 0.000E+00  additional vertical mixing [m^2/s] for tracer #15
2026-05-15 15:38:09,075 [INFO] - handler.py:195 -  Akt_bak(*) = 0.000E+00  additional vertical mixing [m^2/s] for tracer #16
2026-05-15 15:38:09,075 [INFO] - handler.py:195 -  Akt_bak(*) = 0.000E+00  additional vertical mixing [m^2/s] for tracer #17
2026-05-15 15:38:09,075 [INFO] - handler.py:195 -  Akt_bak(*) = 0.000E+00  additional vertical mixing [m^2/s] for tracer #18
2026-05-15 15:38:09,075 [INFO] - handler.py:195 -  Akt_bak(*) = 0.000E+00  additional vertical mixing [m^2/s] for tracer #19
2026-05-15 15:38:09,075 [INFO] - handler.py:195 -  Akt_bak(*) = 0.000E+00  additional vertical mixing [m^2/s] for tracer #20
2026-05-15 15:38:09,075 [INFO] - handler.py:195 -  Akt_bak(*) = 0.000E+00  additional vertical mixing [m^2/s] for tracer #21
2026-05-15 15:38:09,075 [INFO] - handler.py:195 -  Akt_bak(*) = 0.000E+00  additional vertical mixing [m^2/s] for tracer #22
2026-05-15 15:38:09,075 [INFO] - handler.py:195 -  Akt_bak(*) = 0.000E+00  additional vertical mixing [m^2/s] for tracer #23
2026-05-15 15:38:09,075 [INFO] - handler.py:195 -  Akt_bak(*) = 0.000E+00  additional vertical mixing [m^2/s] for tracer #24
2026-05-15 15:38:09,075 [INFO] - handler.py:195 -  Akt_bak(*) = 0.000E+00  additional vertical mixing [m^2/s] for tracer #25
2026-05-15 15:38:09,075 [INFO] - handler.py:195 -  Akt_bak(*) = 0.000E+00  additional vertical mixing [m^2/s] for tracer #26
2026-05-15 15:38:09,075 [INFO] - handler.py:195 -  Akt_bak(*) = 0.000E+00  additional vertical mixing [m^2/s] for tracer #27
2026-05-15 15:38:09,075 [INFO] - handler.py:195 -  Akt_bak(*) = 0.000E+00  additional vertical mixing [m^2/s] for tracer #28
2026-05-15 15:38:09,075 [INFO] - handler.py:195 -  Akt_bak(*) = 0.000E+00  additional vertical mixing [m^2/s] for tracer #29

2026-05-15 15:38:14,800 [WARNING] - handler.py:152 - This job is currently not running (completed). Live updates cannot be provided. See /Users/eilerman/cson-forge-data/cson-forge-run/cson_roms-marbl_v0.1_test-tiny_1procs_20120101-20120102/logs/cstar_worker_20260515_213727.out for job output
Numba: Attempted to fork from a non-main thread, the TBB library may be in an invalid state in the child process.
Numba: Attempted to fork from a non-main thread, the TBB library may be in an invalid state in the child process.

2026-05-15 15:38:14,803 [INFO] - simulation.py:92 - Spatial join of netCDF files 'output_cdr.20120101020000.*.nc' starting
2026-05-15 15:38:14,803 [INFO] - simulation.py:92 - Spatial join of netCDF files 'output_rst.20120102000000.*.nc' starting
2026-05-15 15:38:15,091 [INFO] - simulation.py:101 - Spatial join of '/Users/eilerman/cson-forge-data/cson-forge-run/cson_roms-marbl_v0.1_test-tiny_1procs_20120101-20120102/joined_output/output_cdr.20120101020000.nc' is complete
2026-05-15 15:38:15,094 [INFO] - simulation.py:101 - Spatial join of '/Users/eilerman/cson-forge-data/cson-forge-run/cson_roms-marbl_v0.1_test-tiny_1procs_20120101-20120102/joined_output/output_rst.20120102000000.nc' is complete
2026-05-15 15:38:15,095 [INFO] - runner.py:116 - BlueprintRunner reached a terminal state 'completed'
2026-05-15 15:38:15,095 [INFO] - service.py:322 - Shutting down service.
2026-05-15 15:38:15,095 [INFO] - runner.py:94 - Simulation completed successfully.
Blueprint execution completed